# Generated by Django 4.2.11 on 2024-03-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_member_remove_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rent_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
