# Generated by Django 4.2.11 on 2024-03-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_transaction_rent_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='student',
            new_name='member',
        ),
    ]
